blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/echasnovski/mini.nvim/discussions/new?category=q-a
    about: Ask about configuration and usage of 'mini.nvim'
