name: CI
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "luajit-2.1.0-beta3"
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
    steps:
      - uses: actions/checkout@v2
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.version }}
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
        with:
          luaRocksVersion: 3.3.1
      - name: install busted
        run: |
          luarocks install moonscript
          luarocks install busted
      - name: Run tests
        run: busted -o TAP
